name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish SubtitleEasy Extension
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Build
        run: |
          npm ci
          npm run build
          cd dist && zip -r subtitle_easy.zip . && cd ..
      - name: Upload & release
        uses: mnao305/chrome-extension-upload@v4.0.1
        with:
          file-path: dist/subtitle_easy.zip
          extension-id: ${{ secrets.EXTENSION_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          publish: false
